 const OPEN_TOAST = 'OPEN_TOAST'
 const SAVE_JSON_PLACEHOLDER = 'SAVE_JSON_PLACEHOLDER'
 const LOGIN_STATE = 'LOGIN_STATE'
const CLEAR_JSON_PLACEHOLDER = 'CLEAR_JSON_PLACEHOLDER'

export {
    CLEAR_JSON_PLACEHOLDER,
    OPEN_TOAST,
    SAVE_JSON_PLACEHOLDER,
    LOGIN_STATE
}